name: Dataset (clouds)

on:
  schedule:
    - cron: '10 6 * * *'  # runs daily at 06:10 UTC
  workflow_dispatch: {}

jobs:
  run:
    uses: ./.github/workflows/zyra.yml
    with:
      DATASET_NAME: clouds
    secrets: inherit
